'use client';
import { useEffect, useState } from 'react';
import AppShell from '@/components/AppShell'; import Protected from '@/components/Protected'; import GlassCard from '@/components/GlassCard'; import SectionHeader from '@/components/SectionHeader';
import { useAuth } from '@/components/AuthProvider'; import { useRouter } from 'next/navigation'; import { loadLocal, saveLocal } from '@/lib/storage';

export default function Settings(){return <Protected><AppShell><SettingsInner/></AppShell></Protected>}
function SettingsInner(){
 const {user,signOut,localMode,updateProfile}=useAuth(); const router=useRouter();
 const [saved,setSaved]=useState(false); const [name,setName]=useState(''); const [currency,setCurrency]=useState('INR'); const [aiProvider,setAiProvider]=useState('local'); const [compact,setCompact]=useState(false); const [showDemo,setShowDemo]=useState(true);
 useEffect(()=>{if(!user)return;setName(user.name);setCurrency(user.currency||'INR');const settings=loadLocal('settings',{aiProvider:'local',compact:false,showDemo:true},user.id) as any;setAiProvider(settings.aiProvider||'local');setCompact(Boolean(settings.compact));setShowDemo(settings.showDemo!==false)},[user?.id]);
 async function save(){try{await updateProfile({name:name.trim()||'You',currency});saveLocal('settings',{aiProvider,compact,showDemo},user?.id);setSaved(true);setTimeout(()=>setSaved(false),1800)}catch{setSaved(false)}}
 function resetDemo(){if(!user)return;localStorage.removeItem(`lumina_transactions_${user.id}`);localStorage.removeItem(`lumina_goals_${user.id}`);window.location.href='/'}
 return <div className="page"><div className="topbar"><div><h1>Settings</h1><p>Manage your profile, preferences, AI mode, and account.</p></div><button className="button primary" onClick={save}>{saved?'Saved':'Save changes'}</button></div>
 <div className="settings-grid">
  <GlassCard className="setting-card"><SectionHeader title="Profile" subtitle="How Lumina identifies you."/><div className="field"><label>Name</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="field" style={{marginTop:14}}><label>Email</label><input className="input" value={user?.email??''} disabled/></div><div className="field" style={{marginTop:14}}><label>Currency</label><select className="select" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="INR">INR · ₹</option><option value="USD">USD · $</option><option value="EUR">EUR · €</option><option value="GBP">GBP · £</option></select></div></GlassCard>
  <GlassCard className="setting-card"><SectionHeader title="AI advisor" subtitle="Choose how Lumina should answer when an AI provider is connected."/><div className="field"><label>Provider</label><select className="select" value={aiProvider} onChange={e=>setAiProvider(e.target.value)}><option value="local">Local / demo fallback</option><option value="groq">Groq API</option><option value="openai">OpenAI API</option></select></div><p className="auth-note" style={{marginTop:12}}>Cloud provider keys stay server-side in environment variables. Local mode works without a key.</p></GlassCard>
  <GlassCard className="setting-card"><SectionHeader title="Preferences" subtitle="Small controls that change your workspace."/><div className="setting-row"><span>Compact dashboard cards</span><button type="button" className={`toggle ${compact?'on':''}`} onClick={()=>setCompact(v=>!v)}><i/></button></div><div className="setting-row"><span>Show sample recommendations</span><button type="button" className={`toggle ${showDemo?'on':''}`} onClick={()=>setShowDemo(v=>!v)}><i/></button></div><div className="setting-row"><span>Storage</span><strong>{localMode?'This browser':'Supabase Postgres'}</strong></div></GlassCard>
  <GlassCard className="setting-card"><SectionHeader title="Account" subtitle={localMode?'Local development account':'Cloud account via Supabase'}/><div className="setting-row"><span>Authentication</span><strong>{localMode?'Local email/password':'Email / Google'}</strong></div><div className="setting-row"><span>Data ownership</span><strong>{localMode?'Per local account':'Per Supabase user'}</strong></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:16}}><button className="button" onClick={async()=>{await signOut();router.push('/login')}}>Sign out</button>{localMode&&<button className="button" onClick={resetDemo}>Reset my demo data</button>}</div></GlassCard>
 </div></div>
}
